"""Dropping Appointments table and creating reviews table; removing unnecessary columns from Barber model

Revision ID: 30dfe0a60a78
Revises: b2ec6b4ab766
Create Date: 2024-05-15 10:22:02.741238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30dfe0a60a78'
down_revision = 'b2ec6b4ab766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.Column('barber_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], name=op.f('fk_reviews_barber_id_barbers')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_reviews_client_id_clients')),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.drop_table('appointments')
    with op.batch_alter_table('barbers', schema=None) as batch_op:
        batch_op.drop_column('_password_hash')
        batch_op.drop_column('username')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('_password_hash', sa.VARCHAR(), nullable=True))

    op.create_table('appointments',
    sa.Column('appointment_id', sa.INTEGER(), nullable=False),
    sa.Column('appointment_date', sa.DATETIME(), nullable=True),
    sa.Column('appointment_time', sa.DATETIME(), nullable=True),
    sa.Column('service_type', sa.VARCHAR(), nullable=True),
    sa.Column('barber_id', sa.INTEGER(), nullable=True),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['barber_id'], ['barbers.id'], name='fk_appointments_barber_id_barbers'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='fk_appointments_client_id_clients'),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.drop_table('reviews')
    # ### end Alembic commands ###
