"""Removing available_times and available_dates in the Barber model

Revision ID: 57c22e3fedcd
Revises: 3af4428cd9d8
Create Date: 2024-06-12 22:20:50.749825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '57c22e3fedcd'
down_revision = '3af4428cd9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbers', schema=None) as batch_op:
        batch_op.drop_column('available_times')
        batch_op.drop_column('available_dates')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_dates', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('available_times', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
