"""removing experience column from Barber model

Revision ID: b2ec6b4ab766
Revises: b43a6d3939c7
Create Date: 2024-05-15 09:52:50.741232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ec6b4ab766'
down_revision = 'b43a6d3939c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbers', schema=None) as batch_op:
        batch_op.drop_column('experience')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
